- uses: actions/checkout@v4

- name: Set up JDK 21
  uses: actions/setup-java@v4
  with:
    java-version: '21'
    distribution: 'temurin'
    cache: maven

- name: Generate keypair for authentication (in correct location)
  working-directory: Middleware
  run: |
    mkdir -p src/main/resources/certs
    openssl genpkey -algorithm RSA -out src/main/resources/certs/private.pem -pkeyopt rsa_keygen_bits:2048
    openssl rsa -pubout -in src/main/resources/certs/private.pem -out src/main/resources/certs/public.pem

- name: Clean and test with Maven
  run: mvn clean test
  working-directory: Middleware

- name: Build with Maven
  run: mvn install
  working-directory: Middleware
